remote_theme: simonebortolin/just-the-docs
title: "Hack GPON"
baseurl: 
permalink: '/:title'
search_enabled: true
search:
  # Split pages into sections that can be searched individually
  # Supports 1 - 6, default: 2
  heading_level: 2
  # Maximum amount of previews per search result
  # Default: 3
  previews: 3
  # Maximum amount of words to display before a matched word in the preview
  # Default: 5
  preview_words_before: 5
  # Maximum amount of words to display after a matched word in the preview
  # Default: 10
  preview_words_after: 10
  # Set the search token separator
  # Default: /[\s\-/]+/
  # Example: enable support for hyphenated search words
  tokenizer_separator: /[\s/]+/
  # Display the relative url in search results
  # Supports true (default) or false
  rel_url: true
  # Enable or disable the search button that appears in the bottom right corner of every page
  # Supports true or false (default)
  button: false

plugins:
  - jekyll-seo-tag
  - jekyll-last-modified-at
  - jekyll-redirect-from

color_scheme: "light"
url: "https://hack-gpon.github.io/"
nav_sort: case_sensitive

aux_links:
  '<a href="//github.com/hack-gpon/hack-gpon.github.io" class="btn btn-blue">Telegram <img style="width:auto;height:20px;vertical-align:middle;" src="https://iconape.com/wp-content/png_logo_vector/telegram-new-2019-black-x-logo.png"></a>'
  
#aux_links:
#  "Hack GPON on GitHub":
#    - "//github.com/hack-gpon/hack-gpon.github.io"
#  "Hack GPON on Telegram":
#    - "//t.me/HackGPON"

back_to_top: true
back_to_top_text: "Back to top"

footer_content: "Copyright &copy; 2022. Distributed by an <a href=\"https://github.com/hack-gpon/hack-gpon.github.io/blob/main/LICENCE\">MIT License</a>. <a href=\"privacy-policy\">Privacy Policy</a>."

last_edit_timestamp_script: true

gh_edit_link: true # show or hide edit this page link
gh_edit_link_text: "Edit this page on GitHub"
gh_edit_repository: "https://github.com/hack-gpon/hack-gpon.github.io" # the github URL for your repo
gh_edit_branch: "main" # the branch that your docs is served from
# gh_edit_source: docs # the source that your files originate from
gh_edit_view_mode: "tree"
gh_owner_name: hack-gpon
gh_repository_name: hack-gpon.github.io

whitelist:
  - jekyll-redirect-from

mermaid_enabled: true
mermaid:
  # Version of mermaid library
  # Pick an available version from https://cdn.jsdelivr.net/npm/mermaid/
  version: "9.1.3"
  # Configured theme of mermaid diagrams
  # Pick an avaiable theme from https://mermaid-js.github.io/mermaid/#/theming
  theme: "default"
  # Additional configuration available matching pattern as defined in https://mermaid-js.github.io/mermaid/#/./Setup.
  # For example,
  # logLevel: 'fatal',
  # sequence:
  #   diagramMarginX: 50
  #   actorMargin: 50
  # gantt:
  #   barGap: 4
  #   topPadding: 50

############################################################
# Site configuration for the WebP Generator Plugin
# The values here represent the defaults if nothing is set
webp:
  enabled: true
  
  # The quality of the webp conversion 0 to 100 (where 100 is least lossy)
  quality: 80

  # List of directories containing images to optimize, nested directories will only be checked if `nested` is true
  # By default the generator will search for a folder called `/img` under the site root and process all jpg, png and tiff image files found there.
  img_dir: ["/img","/assets/img/"]

  # Whether to search in nested directories or not
  nested: false

  # add ".gif" to the format list to generate webp for animated gifs as well
  formats: [".jpeg", ".jpg", ".png", ".tiff"]

  # File extensions for animated gif files 
  gifs: [".gif"]

  # Set to true to always regenerate existing webp files
  regenerate: false

  # Local path to the WebP utilities to use (relative or absolute)
  # Omit or leave as nil to use the utilities shipped with the gem, override only to use your local install
  # Eg : "/usr/local/bin/cwebp"
  webp_path: nil

  # List of files or directories to exclude
  # e.g. custom or hand generated webp conversion files
  exclude: []

  # append '.webp' to filename after original extension rather than replacing it.
  # Default transforms `image.png` to `image.webp`, while changing to true transforms `image.png` to `image.png.webp`
  append_ext: false
############################################################
