name: notify-telegram-pr

on:
  pull_request_target:
    types: [opened, reopened]
jobs:
  build:
    name: Notify Telegram
    runs-on: ubuntu-latest
    steps:
      - name: send telegram message on PR opened
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            ${{ github.actor }} created PR ${{ github.event.pull_request.title }}
            See changes: ${{ github.event.pull_request.html_url }}
